### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by ghost** [sepiropht/frontend-master-downloader#2]
I installed your script and tried to download . But this is the ouput I'm getting .

```
(node:14632) UnhandledPromiseRejectionWarning: TypeError: text is not iterable
    at Keyboard.type (/home/aswath/.nvm/versions/node/v8.11.1/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/Input.js:168:24)
    at ElementHandle.type (/home/aswath/.nvm/versions/node/v8.11.1/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/ElementHandle.js:108:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:14632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I'm using Ubuntu 17.10
 node 8.11 (lts)

**Comment by sepiropht** [comment]
Be sure to take the name in the right place for example for the last course https://frontendmasters.com/courses/computer-science-2/ the name of the course is "computer-science-2"

**Comment by ronayumik** [comment]
is it require a paid account?

**Comment by sepiropht** [comment]
Yes , it is required
