### ISSUE TITLE
TimeoutError: waiting for selector ".title a"

### ISSUE THREAD

**Issue by cristimocean** [sepiropht/frontend-master-downloader#31]
I am launching with frontend-master-downloader -u me@gmail.com -p mypass -c "introducing-web-development"
and I get that error.

Full error below:
(node:1620) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector ".title a" failed: timeout 30000ms exceeded
    at new WaitTask (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\DOMWorld.js:432:17)
    at Frame.waitForSelector (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\FrameManager.js:627:47)
    at Frame.<anonymous> (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForSelector (D:\_FEM\downloader\frontend-master-downloader\node_modules\puppeteer\lib\Page.js:1095:29)
    at module.exports (D:\_FEM\downloader\frontend-master-downloader\crawler.js:30:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async D:\_FEM\downloader\frontend-master-downloader\index.js:33:15
(node:1620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Quimy** [comment]
Probably a duplicate: https://github.com/sepiropht/frontend-master-downloader/issues/34
