### ISSUE TITLE
Not Working Either

### ISSUE THREAD

**Issue by Nrevi** [sepiropht/frontend-master-downloader#32]
When executing frontend-master-downloader -u USERNAME -p PASSHERE -c leveldb-crypto (Obviously I put my own details), it fails to download them

```
Try the login ... 

nikodemusb@gmail.com logged 

First scrape all the links... 

(node:26317) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/usr/local/lib/node_modules/frontend-master-downloader/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:26317) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Quimy** [comment]
Probably a duplicate: [https://github.com/sepiropht/frontend-master-downloader/issues/34](url)

**Comment by sepiropht** [comment]
Hey guys sorry for the delay, all the issues with captcha are fixed, and pushed, 
But now you have to set cookie before to use the script. Look at the readme
Let me now if that worked for you !
