### ISSUE TITLE
(node:4132) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by vikiaiteam** [sepiropht/frontend-master-downloader#34]
Try the login ...

(node:4132) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
    at C:\Users\SF\AppData\Roaming\npm\node_modules\frontend-master-downloader\node_modules\puppeteer\lib\NavigatorWatcher.js:69:21
    at async Page.goto (C:\Users\SF\AppData\Roaming\npm\node_modules\frontend-master-downloader\node_modules\puppeteer\lib\Page.js:466:17)
    at async module.exports (C:\Users\SF\AppData\Roaming\npm\node_modules\frontend-master-downloader\crawler.js:16:3)
    at async C:\Users\SF\AppData\Roaming\npm\node_modules\frontend-master-downloader\index.js:33:15
(node:4132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was no
handled with .catch(). (rejection id: 1)
(node:4132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pedrosimao** [comment]
Same here, my Chromium takes too long to start....

**Comment by Quimy** [comment]
For me it was caused by reCAPTCHA. To solve this I run program with `headless` set to false in `crawler.js`. Then I had some more bugs, so I had to fix that too, I will soon push fixed version on my account.

**Comment by Canas** [comment]
> For me it was caused by reCAPTCHA. To solve this I run program with `headless` set to false in `crawler.js`. Then I had some more bugs, so I had to fix that too, I will soon push fixed version on my account.

How do you make it work? Saw your fork and tried to run `index.js` locally, but after the driver goes through every page the program then starts throwing connection errors like crazy:
```
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1088:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
Downloading:0
Downloading:1
Downloading:2
```

**Comment by Quimy** [comment]
If you have links for their cloud, I don't know what may be the cause. Be aware that they can suspend your account due to suspicious activity.

**Comment by pedrosimao** [comment]
Yes. my account was suspended due to using this script. I will have to create a new account...

**Comment by EvilSpark** [comment]
Any free method to create an account there?

**Comment by ibrahimhajjaj** [comment]
Any update on this issue?

**Comment by ibrahimhajjaj** [comment]
Any update on this issue?  @Quimy

**Comment by sepiropht** [comment]
Hey guys sorry for the delay, all the issues with captcha are fixed, and pushed, 
But now you have to set cookie before to use the script. Look at the readme
Let me now if that worked for you !
