### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by octaviotastico** [sepiropht/frontend-master-downloader#36]
```
You are using frontendmaster-downloader 

Try the login ... 

xxxxx logged 

First scrape all the links... 

(node:27797) UnhandledPromiseRejectionWarning: Error: waiting failed: timeout 30000ms exceeded
    at Timeout.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/puppeteer/lib/FrameManager.js:593:58)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:27797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SupratikRulz** [comment]
@octaviotastico I am also facing the same issue

**Comment by AnonymousXuser264** [comment]
me too...

**Comment by octaviotastico** [comment]
Well... To solve this, I'm creating my own downloader. When It's finished (between tomorrow and the day after tomorrow), I'll let you know!

**Comment by sepiropht** [comment]
Hey guys sorry for the delay, all the issues with captcha are fixed, and pushed, 
But now you have to set cookie before to use the script. Look at the readme
Let me now if that worked for you !
